spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: trade
        format_sql: true
        order_inserts: true
        order_updates: true
        #        generate_statistics: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          lob:
            non_contextual_creation: true
    show-sql: false
  datasource:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trade?currentSchema=trade
    username: trade
    password: trade
    initialization-mode: never